-- =====================================================
-- Fix Comment Notification - Ignore Internal Comments
-- Date: 2024-12-25
-- Version: 1.0.1
-- Description: Prevents duplicate notifications for internal system comments
--
-- Issue Fixed:
-- When reviewer marks requisition as reviewed, system creates an internal
-- comment which was triggering a "commented on requisition" notification
-- in addition to the proper "requisition reviewed" notification.
--
-- Fix:
-- Comment notification trigger now ignores internal comments (is_internal = true)
-- =====================================================

BEGIN;

-- ============================================
-- Drop existing comment notification trigger
-- ============================================
DROP TRIGGER IF EXISTS trigger_notify_new_comment ON comments CASCADE;
DROP FUNCTION IF EXISTS notify_new_comment() CASCADE;

-- ============================================
-- Recreate comment notification trigger (FIXED)
-- ============================================

/**
 * Trigger function: Notify when a comment is added (FIXED)
 *
 * Notifies the requisition submitter when someone comments,
 * unless the commenter is the submitter themselves.
 *
 * FIX: Now ignores internal/system comments (is_internal = true)
 * to prevent duplicate notifications when status changes generate
 * automatic comments.
 */
CREATE OR REPLACE FUNCTION notify_new_comment()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  req_submitter UUID;
  req_number VARCHAR(50);
  req_title TEXT;
  commenter_name TEXT;
BEGIN
  -- Skip notifications for internal/system comments
  -- These are auto-generated by status changes and shouldn't notify users
  IF NEW.is_internal = true THEN
    RETURN NEW;
  END IF;

  -- Get requisition information
  SELECT submitted_by, requisition_number, title
  INTO req_submitter, req_number, req_title
  FROM requisitions
  WHERE id = NEW.requisition_id;

  -- Get commenter name
  SELECT full_name INTO commenter_name
  FROM users
  WHERE id = NEW.user_id;

  -- Only notify if commenter is NOT the submitter
  IF req_submitter != NEW.user_id THEN
    PERFORM create_notification(
      req_submitter,
      'requisition_commented',
      'New Comment on Requisition',
      COALESCE(commenter_name, 'Someone') || ' commented on requisition "' || req_title || '"',
      '/requisitions/' || NEW.requisition_id::TEXT
    );
  END IF;

  RETURN NEW;
END;
$$;

-- Create trigger for comment notifications
CREATE TRIGGER trigger_notify_new_comment
  AFTER INSERT ON comments
  FOR EACH ROW
  EXECUTE FUNCTION notify_new_comment();

-- ============================================
-- Verification
-- ============================================

DO $$
DECLARE
  comment_trig_count INTEGER;
BEGIN
  -- Count comment triggers
  SELECT COUNT(*) INTO comment_trig_count
  FROM pg_trigger
  WHERE tgrelid = 'comments'::regclass
    AND tgname LIKE '%notif%';

  RAISE NOTICE '==============================================';
  RAISE NOTICE 'Comment Notification Fix Applied';
  RAISE NOTICE '==============================================';
  RAISE NOTICE 'Comment triggers: %', comment_trig_count;
  RAISE NOTICE '';
  RAISE NOTICE 'FIX APPLIED:';
  RAISE NOTICE '  ✓ Internal/system comments no longer trigger notifications';
  RAISE NOTICE '  ✓ Prevents duplicate notifications on status changes';
  RAISE NOTICE '';
  RAISE NOTICE 'Behavior:';
  RAISE NOTICE '  - User comments: Notify submitter';
  RAISE NOTICE '  - Internal comments (is_internal=true): No notification';
  RAISE NOTICE '  - Status changes: Only workflow notifications sent';
  RAISE NOTICE '==============================================';
END $$;

COMMIT;
